FROM python:3.11-slim

WORKDIR /app

# Installer pip
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copier le code source et les données
COPY app /app/app
COPY data /app/data

# Variables d’environnement
ENV PYTHONPATH=/app
ENV DOCKER_ENV=true

EXPOSE 8501

# Lancer Streamlit avec un niveau de log élevé
ENTRYPOINT ["streamlit", "run", "app/frontend/dashboard.py", \
  "--server.port=8501", \
  "--server.address=0.0.0.0", \
  "--server.headless=true", \
  "--logger.level=debug"]
