FROM python:3.11-slim

WORKDIR /app

# 1. Installer et upgrader pip
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# 2. Copier Copier le dossier 'app/'
COPY app /app/app

# 3. Variables d'env
ENV PYTHONPATH=/app
ENV DOCKER_ENV=true

EXPOSE 8501

# 4. Mode debug Streamlit pour voir d'éventuelles erreurs
ENTRYPOINT ["streamlit", "run", "app/frontend/dashboard.py","--server.port=8501","--server.address=0.0.0.0","--server.headless=true","--logger.level=debug"]
