FROM python:3.11-slim

WORKDIR /app

# Installer curl et pip
RUN apt-get update && apt-get install -y curl \
 && pip install --no-cache-dir --upgrade pip \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY app /app/app

# Copier les fichiers de données directement dans l'image
COPY data /app/data

# Variables d’environnement
ENV PYTHONPATH=/app
ENV DOCKER_ENV=true

EXPOSE 8000

CMD ["uvicorn", "app.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
